# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eGE2CYJctbOdymwd-X1wqhTysiCxR6aS
"""

import numpy as np
import matplotlib.pyplot as plt


A = 1
B = 1
C = 0
D = 0


x = np.linspace(-2 * np.pi, 2 * np.pi, 1000)
y = A * np.sin(B * (x - C)) + D


plt.plot(x, y)
plt.title('Sinusoida grafigi')
plt.xlabel('x')
plt.ylabel('y')
plt.grid()
plt.axhline(0, color='black',linewidth=0.5, ls='--')
plt.axvline(0, color='black',linewidth=0.5, ls='--')
plt.show()

import numpy as np
import matplotlib.pyplot as plt


n = 100


x = np.random.rand(n) * 100
y = np.random.rand(n) * 100


plt.scatter(x, y, c='blue', alpha=0.5, edgecolors='w')
plt.title('Tasodifiy nuqtalar scatter grafigi')
plt.xlabel('X qiymatlari')
plt.ylabel('Y qiymatlari')
plt.grid()
plt.axhline(0, color='black',linewidth=0.5, ls='--')
plt.axvline(0, color='black',linewidth=0.5, ls='--')
plt.show()